### ISSUE TITLE
2024-25 Reaction Wheels Intro Task

### ISSUE THREAD

**Issue by emurray99** [queens-satellite-team/ADCS-Simulink-Simulation#135]
### Description

Use this task to track work done while familiarizing yourself with the Reaction Wheels project for the 2024-25 school year

### To-Do

- [x] Read through closed issues in the "done" column of the reaction wheels project
- [x] Familiarize yourself with documentation related to Reaction wheels in GitHub
- [ ] Familiarize yourself with documentation related to Reaction wheels in Sharepoint
- [ ] Create a summary of the status of the project (identify any unfinished work and make a list of questions you want answered if things are unclear)

Comment links, file paths, updates, anything useful below this issue to help consolidate information!

**Comment by emurray99** [comment]
### Github Issues in Reaction Wheels Project
Done:
#129 - Test analog filter design on solderless breadboard
#49 - Get reaction wheels working with Maxon software, some good discussion in the comments
#59 - Research ticket, contains some useful links to resources, but doesn't contain any key information or discussion
#128 - Research and design ticket for #129 , analog filter

Backlog:
#130 - Satellite mounting of reaction wheels, discusses working with Mech team


### Next Steps (Issues to be created for the following)

- [ ] Replicate work done in #49 to get the reaction wheels functional again! Search for and/or create necessary documentation for the next person to easily set this up
- [ ] Find out if any design work was done for the mounting with Mech (#130)

**Comment by emurray99** [comment]
Still need to cross check with sharepoint to see if these stauses are up to date before creating new issues and closing this issue
