### ISSUE TITLE
2024-25 Magnetorquers Intro Task

### ISSUE THREAD

**Issue by emurray99** [queens-satellite-team/ADCS-Simulink-Simulation#136]
### Description

Use this task to track work done while familiarizing yourself with the Magnetorquers project for the 2024-25 school year

### To-Do

- [ ] Read through closed issues in the "done" column of the Magnetorquers project
- [ ] Familiarize yourself with documentation related to Magnetorquers in GitHub
- [ ] Familiarize yourself with documentation related to Magnetorquers in Sharepoint
- [ ] Create a summary of the status of the project (identify any unfinished work and make a list of questions you want answered if things are unclear)

Comment links, file paths, updates, anything useful below this issue to help consolidate information!

**Comment by emurray99** [comment]
Github issues are all blank and seem to be created by github automation. Will need to look deeper at sharepoint for a status on this project
