### ISSUE TITLE
2024-25 ADCS PCB Intro Task

### ISSUE THREAD

**Issue by emurray99** [queens-satellite-team/ADCS-Simulink-Simulation#137]
### Description

Use this task to track work done while familiarizing yourself with the PCBs project for the 2024-25 school year

### To-Do

- [ ] Read through closed issues in the "done" column of the PCBs project
- [ ] Familiarize yourself with documentation related to PCBs in GitHub
- [ ] Familiarize yourself with documentation related to PCBs in Sharepoint
- [ ] Create a summary of the status of the project (identify any unfinished work and make a list of questions you want answered if things are unclear)

Comment links, file paths, updates, anything useful below this issue to help consolidate information!
